# 1. AŞAMA: DERLEME
FROM node:22 AS build
WORKDIR /app

# Dosyalar FlowraApp içinde olduğu için yolu belirterek kopyalıyoruz
COPY FlowraApp/package*.json ./
RUN npm install

# Tüm kaynak kodları FlowraApp klasöründen konteynere kopyala
COPY FlowraApp/ .

# Angular Build al
RUN npm run build --configuration=production

# 2. AŞAMA: YAYINLAMA (Nginx)
FROM nginx:stable-alpine

# SPA (Single Page Application) Routing hatası için Nginx ayarı
RUN printf "server { \n\
    listen 80; \n\
    location / { \n\
        root /usr/share/nginx/html; \n\
        index index.html index.htm; \n\
        try_files \$uri \$uri/ /index.html; \n\
    } \n\
}" > /etc/nginx/conf.d/default.conf

# DİKKAT: Buradaki yolu angular.json'daki outputPath ile aynı
COPY --from=build /app/dist/FlowraApp/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]